#!/usr/bin/env python

## NOTE: ##
## this setup.py was generated by zero2pypi:
## http://gfxmonk.net/dist/0install/zero2pypi.xml

from setuptools import *
setup(
	packages = find_packages(exclude=['test', 'test.*']),
	description='show and control a running task with an indicator-applet',
	entry_points={'console_scripts': ['indicate-task=indicate_task.main:main']},
	install_requires=['PyGObject'],
	long_description="\n**Note**: This package has been built automatically by\n`zero2pypi <http://gfxmonk.net/dist/0install/zero2pypi.xml>`_.\nIf possible, you should use the zero-install feed instead:\nhttp://gfxmonk.net/dist/0install/indicate-task.xml\n\n----------------\n\nindicate-task\n=============\n\nA command line tool that displays an indicator / persistent\nnotification for the duration of a long-running process (a task).\n\nIt has been tested on Ubuntu 10.10 and Fedora 15, but other distros\nmay not yet have the required support in libnotify / appindicators.\n\nIt can also notify you when the task is complete, and allows you to\ncancel the task or view its output while it is running.\n\nindicate-task echoes stdin to stdout as well as capturing it, so you\ncan wrap a program in an indicator and still get the same output /\nreturn code.\n\n**Note**: indicate task requires the `python-appindicator` package\non Ubuntu. I can't add this to the feed's dependency list, as it\ndoesn't exist (and isn't needed) in any other distro.\n\n------------------------------\n\n## Usage:\n",
	name='indicate-task',
	url='https://github.com/gfxmonk/indicate-task',
	version='0.1.5',
)
